import { useRef } from "react";

export default function Home() {
  const emailInputRef = useRef();
  const feedbackInputRef = useRef();

  const submitFormHandler = (event) => {
    event.preventDefault();
  };

  return (
    <>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Home page</h1>

      <form onSubmit={submitFormHandler}>
        <div>
          <label htmlFor="email">Your Email Address:</label>
          <input type="email" id="email" ref={emailInputRef} />
        </div>

        <div>
          <label htmlFor="feedback">Your Feedback:</label>
          <textarea id="feedback" rows={"3"} ref={feedbackInputRef} />
        </div>
      </form>
    </>
  );
}
